### ISSUE TITLE
pip install conversational-sentence-encoder error

### ISSUE THREAD

**Issue by lytum** [davidalami/ConveRT#1]
pip install conversational-sentence-encoder

**Collecting conversational-sentence-encoder
  Could not find a version that satisfies the requirement conversational-sentence-encoder (from versions: )
No matching distribution found for conversational-sentence-encoder**

Hi, do you know how to solve the above issue? I actually successfully installed the package before, however, today, there is the above mentioned error.

Thanks in advance!

**Comment by davidalami** [comment]
Hello @lytum,
Thank you for reporting! Recently I noticed that some dependencies of conversational-sentence-encoder are not compatible with the latest python versions. Since the stability of this package is tested for python 3.6 only (works perfectly in google colab), I limited the options to python 3.6.* when installing via pip. 
Please let me know if it works fine in python 3.6. Also, if you are willing to do some testing, please try to install the package from source code for your current python distribution and let me know your python version if it works, so that I will include it to supported python versions of the package.

**Comment by lytum** [comment]
In my another project, I installed this library with Python 3.7.6 previously, now it works well. 

Could you include python3.7.6 to the supported python version?

Thanks a lot!

**Comment by davidalami** [comment]
Good to know! 
I did some tests and found that it is possible to install the package with python versions up to 3.7.10, so I will include this version. Unfortunately, the package will not support python>=3.8, since [python 3.8 support requires TensorFlow 2.2 or later](https://www.tensorflow.org/install/pip), but the package requires TensorFlow 1.14.
