### ISSUE TITLE
Tensorflow 2.x compatibility 

### ISSUE THREAD

**Issue by AdelaidaZC** [davidalami/ConveRT#3]
Hello David, 
I've been trying to install ConveRT with the latest tensorflow versions, but it seems that there is no compatibility with tensorflow versions> 1.14. 
I would like to know if there is any chance that your model could be upgraded to work under the latest tensorflow versions.
Thanks

**Comment by davidalami** [comment]
Hello @AdelaidaZC , thank you so much for your interest in ConveRT! 
Yes, it looks like the model can be upgraded if saved as a tensorflow computational graph. It requires much time for research or help from someone experienced in tf 1.x - tf 2.x migration.
Any help on migration would be highly appreciated. Also, pull requests are more than welcome :)

**Comment by davidalami** [comment]
Hey Aaron, thank you for your initiative! 
Unfortunatelly, I do not have the code because I am not an author of these models. The authors worked in PolyAI company and they deleted all the code from their repository for some reasons. The only thing I had was binaries of the tfhub models which I wrapped and presented here as a new repository.

**Comment by aaronbriel** [comment]
@davidalami No worries, and thanks for the quick response!

**Comment by aaronbriel** [comment]
I updated requirements and code to be able to run on TF2 as part of this [PR](https://github.com/davidalami/ConveRT/pull/4).  The primary change was disabling eager execution. Updating the models to TF2 compatible versions, however, would indeed include creating frozen graph models. Fine-tuning these frozen models would not be possible, suggesting that I would likely need to rewrite the ConveRT author's code in Tensorflow2 in order to be able to fine tune it with additional data. It seems like this effort would be outside of the scope of this ticket.

**Comment by davidalami** [comment]
Excellent, @aaronbriel  thank you so much for your contribution! I will test it and then merge :)

**Comment by davidalami** [comment]
The problem is resolved, now we have the support of latest tensorflow versions! Yay! 👍

**Comment by davidalami** [comment]
Great news, I found the ConveRT author's code, and created a new ticket to solve the problem with fine-tuning. 
@aaronbriel, would you like to [take a look](https://github.com/davidalami/ConveRT/issues/5#issue-1330947256)?

**Comment by aaronbriel** [comment]
@davidalami I'm not sure if I will have time for this in the short term, but we will see. Thanks!
