### ISSUE TITLE
Confusion on the ability of ConveRT

### ISSUE THREAD

**Issue by kaizhuanren** [davidalami/ConveRT#8]
I have read the paper and have a question: why can this model achieve better performance with fewer parameters and less pretraining data? My experimental results are similar to those reported in the paper, showing that this model has superior capabilities compared to RoBERTa and MPNet that can provide better sentence embedding

**Comment by davidalami** [comment]
Hello @kaizhuanren , thanks for your question! 
Honestly, I’m still wondering about it too - I just packaged the model for distribution here because used it a lot for different projects. The authors might have sprinkled some magic in there, probably the best way to get this info is to contact one of them.
Cheers!

**Comment by kaizhuanren** [comment]
Thank you for your reply,I will try to contact with the authors to learn about more details.
