### ISSUE TITLE
Seeking Guidance on Sharing Experience: Migrating the Model from TensorFlow to PyTorch

### ISSUE THREAD

**Issue by kaizhuanren** [davidalami/ConveRT#9]
In fact,this is my first time to use the model based on tf, which brings me a awful experience. So I decided to port the model to PyTorch to better suit my next work. 

So far, I have successfully implemented the Single-context model according to the details provided in the paper. In the coming days, I will be focusing on adapting the tokenizer and the pretraining hyperparameters. For this purpose, I plan to conduct pretraining on two RTX4090 GPUs, which should not exceed 36 hours.

One thing that's holding me back is uncertainty around the licensing. I don't know enough about the lisence. So I'm unsure if sharing my migrated code and models would infringe on any rights. I’ve tried reaching out to the original authors and PolyAI staff for consulting the license but haven’t received a response yet.

**Comment by davidalami** [comment]
Hey @kaizhuanren !
I completely understand your frustration by the experience with the old tf model. The porting to PyTorch is a great idea. I remember that a couple years ago there was an incomplete implementation on GitHub, but lost it.
I am not a lawyer, but if you implement a model from scratch based solely on its architecture as described in the research paper, you generally do not violate licensing agreements. The ideas and algorithms described in academic papers are usually not subject to copyright. Since the paper does not explicitly state copyright restrictions, you are free to reimplement it. You can publish or share your implementation, provided it doesn't use proprietary components, pre-trained weights, or datasets protected by specific licenses. If you would like to follow the best practices from ethical point of view, give proper credit to the authors of the paper whose architecture you implemented.
Wishing you all the best with your endeavour!
